@startuml
participant Client
participant SimpleHttpServer
participant ThreadPool
participant Worker
SimpleHttpServer->SimpleHttpServer:设置端口和根路径
SimpleHttpServer->ThreadPool:启动线程池
deactivate SimpleHttpServer
activate ThreadPool
ThreadPool->SimpleHttpServer
deactivate ThreadPool
activate Client
Client->SimpleHttpServer:建立连接
activate ThreadPool
SimpleHttpServer->ThreadPool:包装HttpRequestHandler
activate Worker
ThreadPool->Worker:Worker处理
ThreadPool->SimpleHttpServer:异步返回
deactivate ThreadPool
Worker->Worker:处理请求资源生成相应内容
Worker->Client:输出内容到客户端
deactivate Worker
deactivate Client

@enduml